apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cached-property-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
