apiVersion: v1
kind: Service
metadata:
  name: {{ include "property-swipe.fullname" . }}
  labels:
    {{- include "property-swipe.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.port }}
  selector:
    {{- include "property-swipe.selectorLabels" . | nindent 4 }}
